### ISSUE TITLE
v2.updateManager is not a function

### ISSUE THREAD

**Issue by trevans24** [den-materials/modeling-tunr#1]
http://stackoverflow.com/questions/37058514/angular-js-typeerror-v2-example-is-not-a-function-error
http://stackoverflow.com/questions/32003458/angularjs-error-typeerror-v2-login-is-not-a-function
Jacy said something with form name, even with no form actually named. 
Cam and Alexi have the same error

**Comment by ZebGirouard** [comment]
All set now, great work, Troy!
